version: "2"
services:

  vtc-esign-vertcoind:
    image: lukechilds/vertcoind
    expose:
      - "8332"
    ports:
      - "8333:8333"
    volumes:
      - ./data/vertcoind:/data
    command: -rpcuser=middleware -rpcpassword=middleware -txindex -testnet -addnode=jlovejoy.mit.edu -addnode=10.200.0.1

  vtc-esign-middleware:
    image: vtc-esign-middleware
    depends_on:
      - "vtc-esign-vertcoind"
    environment:
      - VERTCOIND_HOST=vtc-esign-vertcoind
    expose:
      - "8888"
    volumes:
      - ./data/vertcoind/testnet3/blocks:/blocks
      - ./data/index:/index

  vtc-esign-proxy:
    image: vtc-esign-proxy
    depends_on:
      - "vtc-esign-middleware"
      - "vtc-esign-frontend"
    expose:
      - "80"
      - "443"

  vtc-esign-frontend:
    image: vtc-esign-frontend
    expose:
      - "80"

networks:
  default:
    external:
      name: vtc-esignature