version: "2"
services:

  vertcoind-test:
    image: lukechilds/vertcoind
    restart: always
    expose:
      - "8332"
      - "8333"
    ports:
      - "15889:15889"
    volumes:
      - ./data/test/vertcoind:/data
    command: -rpcuser=middleware -rpcpassword=middleware -testnet -addnode=jlovejoy.mit.edu -addnode=gertjaap.ddns.net -txindex

  vtc-middleware-cpp-test:
    image: vtc-wallet-middleware
    restart: always
    environment:
      - VERTCOIND_HOST=vertcoind-test
    expose:
      - "8888"
    volumes:
      - ./data/test/vertcoind/testnet3/blocks:/blocks
      - ./data/test/index:/index

networks:
  default:
    external:
      name: vertcoin-middleware